version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
  api:
    build:
      context: .
    image: i-know-api:local
    network_mode: "host"
    volumes:
      - ./spec:/go/src/github.com/sasso/i-know-api/spec
